services:
  dev:
    build: .
    container_name: team_binder_dev
    entrypoint: /bin/bash
    user: "${HOST_UID}:${HOST_GID}"
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/devuser/workspace
      - ~/.gitconfig:/home/devuser/.gitconfig:ro
    working_dir: /home/devuser/workspace